# Site settings
title: Nathan Handler's Blog
email: nathan.handler@gmail.com
description: "Nathan Handler's Blog"
baseurl: "/blog"
url: "http://nhandler.com"
twitter_username: nathanhandler
github_username:  nhandler
disqus:           nhandler

link-tags: false

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title.html
# theme: beautiful-jekyll
